const PRESCRITOS_HERMES = [
  "Tira un paquete de pañuelos por la ventana",
  "Sobrevive en un LMS como Amy en Outcome Memories",
  "Sobrevive en un LMS como Tails en Outcome Memories",
  "Sobrevive en un LMS como Metal Sonic en Outcome Memories",
  "Sobrevive en un LMS como Eggman en Outcome Memories",
  "Sobrevive en un LMS como Silver en Outcome Memories",
  "Sobrevive en un LMS como Blaze en Outcome Memories",
  "Realiza tiradas en cualquier gacha hasta que consigas una recompesa de alta rareza",
  "Termina un capítulo de una serie que estés viendo/te hagan ver",
  "Vence al Roaring Knight sin recibir daño",
  "Vence al Roaring Knight sin la muerte de ningún aliado",
  "Págame una cantidad de dinero superior a 5 euros",
  "Consigue un check en un randomizer",
  "Termina una mirror dungeon entera con cualquier equipo",
  "Realiza un full combo en una canción en su dificultad más alta, debe ser tu primera vez jugando la canción",
  "Completa el semanal de ZZZ con tu equipo menos jugado",
  "Tienes un minuto para crashear Garry's Mod",
  "Consigue un logro en Steam",
  "Completa un Death Wish, si juegas uno que ya te has pasado, deberás hacerlo en menor tiempo",
  "Haz una boss song sin padecer",
];
