const PRESCRITOS_COMBATE = ["Realiza un railway","Realiza una luxcavación de exp","Realiza una luxcavación de hilo","Enfréntate contra Ricardo", "Enfréntate contra Lei Heng", "Realiza una Mirror Dungeon"];

const PRESCRITOS_ESTADO = [
  "Bleed",
  "Poise",
  "Rupture",
  "Tremor",
  "Charge",
  "Burn",
  "Sinking",
  "Unique Charge",
];

const IDENTIDADES_POR_PECADOR = {
  "Yi Sang": ["LCE E.G.O::Dimension Shredder", "The House of Spiders: The Index Nursefather]","Heishou Pack - Wu Branch Adept","N Corp. E.G.O::Fell Bullet","Liu Assoc. South Section 3","Lobotomy E.G.O::Solemn Lament","The Ring Pointillist Student","W Corp. L3 Cleanup Agent","Effloresced E.G.O::Spicebush","Blade Lineage Salsu","LCE E.G.O::Lantern","Dieci Assoc. South Section 4","The Pequod First Mate","Molar Office Fixer","Seven Assoc. South Section 6","LCB Sinner JAJAJAJAJAJ"],
  "Faust": ["Dawn Office Fixer","The House of Spiders: The Ring Apprentice","The Index Proselyte:【Paper Slip】","Shi East Section 3","Heishou Pack - Mao Branch Adept","LCE E.G.O::Ardor Blossom Star","MultiCrack Office Rep","Blade Lineage Salsu","Lobotomy E.G.O::Regret","Seven Assoc. South Section 4","The One Who Grips","Wuthering Heights Butler","Zwei Assoc. South Section 4","Lobotomy Corp. Remnant","W Corp. L2 Cleanup Agent","LCB Sinner JAJAJAJAJAJ"],
  "Don Quixote": ["The Index Proxy - Effloresced E.G.O::Procuration","Heishou Pack - Wei Branch","Lobotomy E.G.O::In the Name of Love and Hate","Cinq East Section 3","The Manager of La Manchaland","T Corp. Class 3 Collection Staff","The Middle Little Sister","Cinq Assoc. South Section 5 Director","W Corp. L3 Cleanup Agent","Blade Lineage Salsu","Lobotomy E.G.O::Lantern","N Corp. Mittelhammer","Shi Assoc. South Section 5 Director","LCE E.G.O::Lantern","LCB Sinner JAJAJAJAJAJ"],
  "Ryoshu": ["Haute Couture::Le Noir Footwear Hall","Blade of the House of Spiders","Lobotomy E.G.O::Faint Aroma & Solitude","Drifting Blade of Hongyuan","N Corp. E.G.O:: Contempt, Awe","Heishou Pack - Mao Branch","Lobotomy E.G.O:: Red Eyes & Penitence","Edgar Family Chief Butler","W Corp. L3 Cleanup Agent","R.B. Chef de Cuisine","R.B. Chef de Cuisine","District 20 Yurodivy","Liu Assoc. South Section 4","LCCB Assistant Manager","Seven Assoc. South Section 6","LCB Sinner JAJAJAJAJAJ"],
  "Meursault": ["The Ring Fauvist Student","Lobotomy E.G.O:: Hornet【Alteration】","The Prince of La Manchaland","The Thumb East Capo ||||","Cinq Assoc. West Section 3","Dieci Assoc. South Section 4 Director","Blade Lineage Mentor","R Corp. 4th Pack Rhino","N Corp. Großhammer JKAJKSAJKSJAAJSK","Dead Rabbits Boss","The Middle Little Brother","Rosespanner Workshop Fixer","Liu Assoc. South Section 6","LCE E.G.O::Lantern","LCB Sinner JAJAJAJAJAJ"],
  "Hong Lu": ["Cinq Assoc. East Section 3","S Corp. Ch'unokkun","The House of Spiders: The Ring Nursefather","The Lord of Hongyuan","R Corp. 4th Pack Reindeer","Full-Stop Office Rep","District 20 Yurodivy","Dieci Assoc. South Section 4","K Corp. Class 3 Excision Staff","Tingtang Gang Gangleader","Fanghunt Office Fixer","Hook Office Fixer","W Corp. L2 Cleanup Agent","Liu Assoc. South Section 5","Kurokumo Clan Wakashu","LCB Sinner JAJAJAJAJAJ"],
  "Heathcliff": ["The House of Spiders: The Thumb Apprentice","The Middle Big Brother","Heishou Pack - You Branch Adept","W Corp. L4 Cleanup Agent - CCA","Kurokumo Clan Wakashu","Full-Stop Office Fixer","Wild Hunt","Öufi South Section 3","The Pequod Harpooneer","Lobotomy E.G.O::Sunshower","R Corp. 4th Pack Rabbit","MultiCrack Office Fixer","Seven Assoc. South Section 4","N Corp. Kleinhammer","Shi Assoc. South Section 5","LCB Sinner JAJAJAJAJAJ"],
  "Ishmael": ["Haute Couture::Boutique du Rouge","LCD OSIR Team","The House of Spiders: The Middle Apprentice","Jeong's Office Rep","Family Hierarch Candidate","Kurokumo Clan Captain","Zwei Assoc. West Section 3","The Pequod Captain","Molar Boatworks Fixer","Liu Assoc. South Section 4","R Corp. 4th Pack Reindeer","Edgar Family Butler","Lobotomy E.G.O::Sloshing","Shi Assoc. South Section 5","LCCB Assistant Manager","LCB Sinner JAJAJAJAJAJ"],
  "Rodion": ["Haute Couture::Alteration Shop","The House of Spiders: The Thumb Nursefather","The Ring Fauvist Docent","R Corp. 4th Pack Reindeer","Lobotomy E.G.O:: The Sword Sharpened with Tears","Heishou Pack - Si Branch","The Princess of La Manchaland","Devyat' Assoc. North Section 3","Liu Assoc. South Section 4 Director","Dieci Assoc. South Section 4","Rosespanner Workshop Rep","Kurokumo Clan Wakashu","T Corp. Class 2 Collection Staff","Zwei Assoc. South Section 5","N Corp. Mittelhammer","LCCB Assistant Manager","LCB Sinner JAJAJAJAJAJ"],
  "Sinclair": ["The House of Spiders: The Pinky Apprentice","Heishou Pack - You Branch","The Thumb East Soldato ||","The Middle Little Brother","Devyat' Assoc. North Section 3","Dawn Office Fixer","Cinq Assoc.South Section 4 Director","The One Who Shall Grip","Blade Lineage Salsu","Zwei Assoc. West Section 3","Molar Boatworks Fixer","Lobotomy E.G.O::Red Sheet","Zwei Assoc. South Section 6","Los Mariachis Jefe","LCB Sinner JAJAJAJAJAJ"],
  "Outis": ["The House of Spiders: The Middle Nursefather","LCA Udjat Vanguard Team 3 Leader","T Corp. Class 3 VDCU Staff","Heishou Pack - Mao Branch","The Barber of La Manchaland","W Corp. L3 Cleanup Captain","Wuthering Heights Chief Butler","Lobotomy E.G.O::Magic Bullet","Molar Office Fixer","Seven Assoc. South Section 6 Director","The Ring Pointillist Student","Cinq Assoc.South Section 4","Blade Lineage Salsu","G Corp. Head Manager","LCB Sinner JAJAJAJAJAJ"],
  "Gregor": ["Dawn Office Rep","LCE E.G.O::AEDD","Lobotomy E.G.O::Lamp","Night Awl Capitano","Heishou Pack - Si Branch","Firefist Office Survivor","The Priest of La Manchaland","Edgar Family Heir","Twinhook Pirates First Mate","Zwei Assoc. South Section 4","G Corp. Manager Corporal","Kurokumo Clan Captain","Rosespanner Workshop Fixer","R.B. Sous-chef","Liu Assoc. South Section 6","LCB Sinner JAJAJAJAJAJ"],
};